import { nanoid } from "nanoid";
import productPicture from "../img/products/indexImgProducts";

const articlesList = [
  {
    id: nanoid(8),
    productName: ["Apple", "Pomme"],
    category: "fruit",
    origin: ["Florida", "Floride"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgApple,
  },
  {
    id: nanoid(8),
    productName: ["Apricot", "Abricot"],
    category: "fruit",
    origin: ["Maroc", "Maroc"],
    price: 1.69,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgApricot,
  },
  {
    id: nanoid(8),
    productName: ["Banana", "Banane"],
    category: "fruit",
    origin: ["Ivory Coast", "Côte d'Ivoire"],
    price: 1.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBanana,
  },
  {
    id: nanoid(8),
    productName: ["BlueBerry", "Myrtilles"],
    category: "fruit",
    origin: ["France", "France"],
    price: 0.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBlueBerry,
  },
  {
    id: nanoid(8),
    productName: ["Cherry", "Cerise"],
    category: "fruit",
    origin: ["France", "France"],
    price: 4.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCherry,
  },
  {
    id: nanoid(8),
    productName: ["Kiwi", "Kiwi"],
    category: "fruit",
    origin: ["Florida", "Floride"],
    price: 0.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgKiwi,
  },
  {
    id: nanoid(8),
    productName: ["Lemon ", "Citron"],
    category: "fruit",
    origin: ["Italy", "Italie"],
    price: 0.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgLemon,
  },
  {
    id: nanoid(8),
    productName: ["Mango", "Mangue"],
    category: "fruit",
    origin: ["Ivory Coast", "Côte d'Ivoire"],
    price: 1.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgMango,
  },
  {
    id: nanoid(8),
    productName: ["Avocado", "Avocat"],
    category: "fruit",
    origin: ["Spain", "Espagne"],
    price: 0.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgAvocado,
  },
  {
    id: nanoid(8),
    productName: ["StrawBerry", "Fraise"],
    category: "fruit",
    origin: ["France", "France"],
    price: 2.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgStrawBerry,
  },
  {
    id: nanoid(8),
    productName: ["Grapes", "Raisin"],
    category: "fruit",
    origin: ["Italy", "Italie"],
    price: 2.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGrapes,
  },
  {
    id: nanoid(8),
    productName: ["Watermelon", "Pastèque"],
    category: "fruit",
    origin: ["Spain", "Espagne"],
    price: 2.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgWaterMelon,
  },
  {
    id: nanoid(8),
    productName: ["Dragonfruit", "Fruit du dragon"],
    category: "fruit",
    origin: ["Vietnam", "Vietnam"],
    price: 2.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgDragonFruit,
  },
  {
    id: nanoid(8),
    productName: ["Orange", "Orange"],
    category: "fruit",
    origin: ["Florida", "Floride"],
    price: 0.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgOrange,
  },
  {
    id: nanoid(8),
    productName: ["Papaya", "Papaye"],
    category: "fruit",
    origin: ["Ivory Coast", "Côte d'Ivoire"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPapaya,
  },
  {
    id: nanoid(8),
    productName: ["Pineapple", "Ananas"],
    category: "fruit",
    origin: ["Ivory Coast", "Côte d'Ivoire"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPineApple,
  },
  {
    id: nanoid(8),
    productName: ["Pomegranate", "Grenade"],
    category: "fruit",
    origin: ["Vietnam", "Vietnam"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPomeGranate,
  },
  {
    id: nanoid(8),
    productName: ["Mangosteen", "Mangoustan"],
    category: "fruit",
    origin: ["Vietnam", "Vietnam"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgMangosteen,
  },
  {
    id: nanoid(8),
    productName: ["Pear", "Poire"],
    category: "fruit",
    origin: ["France", "France"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPear,
  },
  {
    id: nanoid(8),
    productName: ["Plums", "Prune"],
    category: "fruit",
    origin: ["France", "France"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPlums,
  },
  {
    id: nanoid(8),
    productName: ["GrapeFruit", "Pamplemousse"],
    category: "fruit",
    origin: ["France", "France"],
    price: 0.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGrapeFruit,
  },
  {
    id: nanoid(8),
    productName: ["Melon", "Melon"],
    category: "fruit",
    origin: ["France", "France"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgMelon,
  },
  {
    id: nanoid(8),
    productName: ["Damson", "Quetsche"],
    category: "fruit",
    origin: ["France", "France"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgDamson,
  },
  {
    id: nanoid(8),
    productName: ["Papaya", "Papaye"],
    category: "fruit",
    origin: ["France", "France"],
    price: 1.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPapaya,
  },
  {
    id: nanoid(8),
    productName: ["Coconut", "Noix de coco"],
    category: "fruit",
    origin: ["Tahiti", "Tahiti"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCoconut,
  },
  {
    id: nanoid(8),
    productName: ["Peach", "Pêche"],
    category: "fruit",
    origin: ["France", "France"],
    price: 2.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPeach,
  },
  {
    id: nanoid(8),
    productName: ["Custard Apple", "Chérimolier"],
    category: "fruit",
    origin: ["India", "Inde"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCustardApple,
  },
  {
    id: nanoid(8),
    productName: ["Guava", "Goyave"],
    category: "fruit",
    origin: ["Brazil", "Brésil"],
    price: 1.79,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGuava,
  },
  {
    id: nanoid(8),
    productName: ["Pumpkin", "Citrouille"],
    category: "fruit",
    origin: ["Brazil", "Brésil"],
    price: 2.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPumpkin,
  },
  {
    id: nanoid(8),
    productName: ["Lychee", "Litchi"],
    category: "fruit",
    origin: ["China", "Chine"],
    price: 1.29,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgLychee,
  },
  {
    id: nanoid(8),
    productName: ["Sapodilla", "Sapotille"],
    category: "fruit",
    origin: ["Caribbean", "Caraïbes"],
    price: 2.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgSapodilla,
  },
  {
    id: nanoid(8),
    productName: ["Dates", "Dates"],
    category: "fruit",
    origin: ["Sahara", "Sahara"],
    price: 2.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgDates,
  },
  {
    id: nanoid(8),
    productName: ["Fig", "Figue"],
    category: "fruit",
    origin: ["Sahara", "Sahara"],
    price: 2.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgFig,
  },
  {
    id: nanoid(8),
    productName: ["Grewia", "Grewia"],
    category: "fruit",
    origin: ["Asia", "Asia"],
    price: 1.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGrewia,
  },
  {
    id: nanoid(8),
    productName: ["Carambola", "Carambole"],
    category: "fruit",
    origin: ["Asia", "Asia"],
    price: 1.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCarambola,
  },
  {
    id: nanoid(8),
    productName: ["Cranberry", "Cranberry"],
    category: "fruit",
    origin: ["U.S.A", "U.S.A"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCranberry,
  },
  {
    id: nanoid(8),
    productName: ["Hanepoot", "Raisin blanc"],
    category: "fruit",
    origin: ["France", "France"],
    price: 1.69,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgHanepoot,
  },
  {
    id: nanoid(8),
    productName: ["JackFruit", "Jacquier"],
    category: "fruit",
    origin: ["India", "Inde"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgJackFruit,
  },
  {
    id: nanoid(8),
    productName: ["JamonFruit", "Jamblon"],
    category: "fruit",
    origin: ["India", "Inde"],
    price: 1.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgJamonFruit,
  },
  {
    id: nanoid(8),
    productName: ["Mulberry", "Mûre"],
    category: "fruit",
    origin: ["Asia", "Asia"],
    price: 2.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgMulberry,
  },
  {
    id: nanoid(8),
    productName: ["Persimmon", "Kaki"],
    category: "fruit",
    origin: ["China", "China"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPersimmon,
  },
  {
    id: nanoid(8),
    productName: ["Quince", "Coing"],
    category: "fruit",
    origin: ["Saudi Arabia", "Arabia"],
    price: 2.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgQuince,
  },
  {
    id: nanoid(8),
    productName: ["Redcurrant", "Groseilles"],
    category: "fruit",
    origin: ["Southern America", "Amérique du Sud"],
    price: 2.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgRedCurrant,
  },
  {
    id: nanoid(8),
    productName: ["Jujube", "Jujube"],
    category: "fruit",
    origin: ["Central Asia", "Asie Centrale"],
    price: 2.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgJujube,
  },
  {
    id: nanoid(8),
    productName: ["Elderberry", "Sureau"],
    category: "fruit",
    origin: ["Greece", "Grèce"],
    price: 1.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgElderBerry,
  },
  {
    id: nanoid(8),
    productName: ["Olive", "Olive"],
    category: "fruit",
    origin: ["Italy", "Italie"],
    price: 4.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgOlive,
  },
  {
    id: nanoid(8),
    productName: ["Tamarind", "Tamarin"],
    category: "fruit",
    origin: ["Asia", "Asie"],
    price: 2.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgTamarind,
  },
  {
    id: nanoid(8),
    productName: ["Cashew Apple", "Pomme de Cajou"],
    category: "fruit",
    origin: ["Brazil", "Brésil"],
    price: 1.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCashewApple,
  },
  {
    id: nanoid(8),
    productName: ["Sugarcane", "Canne à sucre"],
    category: "fruit",
    origin: ["New Guinea", "Nouvelle Guinée"],
    price: 1.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgSugarCane,
  },
  {
    id: nanoid(8),
    productName: ["Shaddock", "Pomelo"],
    category: "fruit",
    origin: ["Malaysia", "Malaisie"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgShaddock,
  },
  {
    id: nanoid(8),
    productName: ["GooseBerry", "Groseille"],
    category: "fruit",
    origin: ["Malaysia", "Malaisie"],
    price: 1.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGooseBerry,
  },
  {
    id: nanoid(8),
    productName: ["Durian", "Durian"],
    category: "fruit",
    origin: ["Asia", "Asie"],
    price: 2.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgDurian,
  },
  {
    id: nanoid(8),
    productName: ["Raspberry", "Framboise"],
    category: "fruit",
    origin: ["France", "France"],
    price: 1.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgRaspBerry,
  },

  {
    id: nanoid(8),
    productName: ["carrot", "carotte"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCarrot,
  },
  {
    id: nanoid(8),
    productName: ["broccoli", "brocoli"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBroccoli,
  },
  {
    id: nanoid(8),
    productName: ["tomato", "tomate"],
    category: "vegetable",
    origin: ["Spain", "Espagne"],
    price: 1.29,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgTomato,
  },
  {
    id: nanoid(8),
    productName: ["potatoe", "pomme de terre"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.89,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPotato,
  },
  {
    id: nanoid(8),
    productName: ["onion", "oignon"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.69,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgOnion,
  },
  {
    id: nanoid(8),
    productName: ["cucumber", "concombre"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.19,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCucumber,
  },
  {
    id: nanoid(8),
    productName: ["lettuce", "laitue"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgLettuce,
  },
  {
    id: nanoid(8),
    productName: ["bell-pepper", "poivron"],
    category: "vegetable",
    origin: ["Spain", "Espagne"],
    price: 1.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBellPepper,
  },
  {
    id: nanoid(8),
    productName: ["zucchini", "courgette"],
    category: "vegetable",
    origin: ["Italy", "Italie"],
    price: 1.39,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgZucchini,
  },
  {
    id: nanoid(8),
    productName: ["spinach", "épinard"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.99,
    package: "500g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgSpinach,
  },
  {
    id: nanoid(8),
    productName: ["green-beans", "haricot vert"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.29,
    package: "500g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGreenBeans,
  },
  {
    id: nanoid(8),
    productName: ["cauliflower", "chou-fleur"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.79,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCauliFlower,
  },
  {
    id: nanoid(8),
    productName: ["mushroom", "champignon"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.49,
    package: "250g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgMushroom,
  },
  {
    id: nanoid(8),
    productName: ["radish", "radis"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgRadish,
  },
  {
    id: nanoid(8),
    productName: ["cabbage", "chou"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.29,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCabbage,
  },
  {
    id: nanoid(8),
    productName: ["sweet-potatoe", "Patate douce"],
    category: "vegetable",
    origin: ["Spain", "Espagne"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgSweetPotatoe,
  },
  {
    id: nanoid(8),
    productName: ["artichoke", "artichaut"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgArtichoke,
  },
  {
    id: nanoid(8),
    productName: ["eggplant", "aubergine"],
    category: "vegetable",
    origin: ["Spain", "Espagne"],
    price: 1.79,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgEggPlant,
  },
  {
    id: nanoid(8),
    productName: ["asparagus", "asperge"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 3.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgAsparagus,
  },
  {
    id: nanoid(8),
    productName: ["beetroot", "betterave"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.29,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBeetRoot,
  },
  {
    id: nanoid(8),
    productName: ["celery", "céleri"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCelery,
  },
  {
    id: nanoid(8),
    productName: ["garlic", "ail"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.79,
    package: "100g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGarlig,
  },
  {
    id: nanoid(8),
    productName: ["ginger", "gingembre"],
    category: "vegetable",
    origin: ["India", "Inde"],
    price: 1.99,
    package: "100g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGinger,
  },
  {
    id: nanoid(8),
    productName: ["leek", "poireau"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.29,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgLeek,
  },
  {
    id: nanoid(8),
    productName: ["Peas", "Petits pois"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPeas,
  },
  {
    id: nanoid(8),
    productName: ["turnip", "navet"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.19,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgTurnip,
  },
  {
    id: nanoid(8),
    productName: ["rhubarb", "rhubarbe"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgRhubarb,
  },
  {
    id: nanoid(8),
    productName: ["scallion", "oignon vert"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgScallion,
  },
  {
    id: nanoid(8),
    productName: ["fennel", "fenouil"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.79,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgFennel,
  },
  {
    id: nanoid(8),
    productName: ["parsnip", "panais"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgParsnip,
  },
  {
    id: nanoid(8),
    productName: ["kale", "chou frisé"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgKale,
  },
  {
    id: nanoid(8),
    productName: ["watercress", "cresson"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.79,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgWaterCress,
  },
  {
    id: nanoid(8),
    productName: ["okra", "gombo"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgOkra,
  },
  {
    id: nanoid(8),
    productName: ["brussels-sprout", "chou de Bruxelles"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBrusselsSprout,
  },
  {
    id: nanoid(8),
    productName: ["swiss-chard", "blette"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.69,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgSwissChard,
  },
  {
    id: nanoid(8),
    productName: ["bok-choy", "Chou chinois"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBokChoy,
  },
];

export default articlesList;
