import { nanoid } from "nanoid";
import productPicture from "../img/products/indexImgProducts.jsx";
const vegetablesList = [
  {
    id: nanoid(8),
    productName: ["carrot", "carotte"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCarrot,
  },
  {
    id: nanoid(8),
    productName: ["broccoli", "brocoli"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBroccoli,
  },
  {
    id: nanoid(8),
    productName: ["tomato", "tomate"],
    category: "vegetable",
    origin: ["Spain", "Espagne"],
    price: 1.29,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgTomato,
  },
  {
    id: nanoid(8),
    productName: ["potatoe", "pomme de terre"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.89,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPotato,
  },
  {
    id: nanoid(8),
    productName: ["onion", "oignon"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.69,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgOnion,
  },
  {
    id: nanoid(8),
    productName: ["cucumber", "concombre"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.19,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCucumber,
  },
  {
    id: nanoid(8),
    productName: ["lettuce", "laitue"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgLettuce,
  },
  {
    id: nanoid(8),
    productName: ["bell-pepper", "poivron"],
    category: "vegetable",
    origin: ["Spain", "Espagne"],
    price: 1.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBellPepper,
  },
  {
    id: nanoid(8),
    productName: ["zucchini", "courgette"],
    category: "vegetable",
    origin: ["Italy", "Italie"],
    price: 1.39,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgZucchini,
  },
  {
    id: nanoid(8),
    productName: ["spinach", "épinard"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.99,
    package: "500g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgSpinach,
  },
  {
    id: nanoid(8),
    productName: ["green-beans", "haricot vert"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.29,
    package: "500g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGreenBeans,
  },
  {
    id: nanoid(8),
    productName: ["cauliflower", "chou-fleur"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.79,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCauliFlower,
  },
  {
    id: nanoid(8),
    productName: ["mushroom", "champignon"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.49,
    package: "250g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgMushroom,
  },
  {
    id: nanoid(8),
    productName: ["radish", "radis"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgRadish,
  },
  {
    id: nanoid(8),
    productName: ["cabbage", "chou"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.29,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgCabbage,
  },
  {
    id: nanoid(8),
    productName: ["sweet-potatoe", "Patate douce"],
    category: "vegetable",
    origin: ["Spain", "Espagne"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgSweetPotatoe,
  },
  {
    id: nanoid(8),
    productName: ["artichoke", "artichaut"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.99,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgArtichoke,
  },
  {
    id: nanoid(8),
    productName: ["eggplant", "aubergine"],
    category: "vegetable",
    origin: ["Spain", "Espagne"],
    price: 1.79,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgEggPlant,
  },
  {
    id: nanoid(8),
    productName: ["asparagus", "asperge"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 3.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgAsparagus,
  },
  {
    id: nanoid(8),
    productName: ["beetroot", "betterave"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.29,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBe,
  },
  {
    id: nanoid(8),
    productName: ["celery", "céleri"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBeetRoot,
  },
  {
    id: nanoid(8),
    productName: ["garlic", "ail"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.79,
    package: "100g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGarlig,
  },
  {
    id: nanoid(8),
    productName: ["ginger", "gingembre"],
    category: "vegetable",
    origin: ["India", "Inde"],
    price: 1.99,
    package: "100g",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgGinger,
  },
  {
    id: nanoid(8),
    productName: ["leek", "poireau"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.29,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgLeek,
  },
  {
    id: nanoid(8),
    productName: ["Peas", "Petits pois"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgPeas,
  },
  {
    id: nanoid(8),
    productName: ["turnip", "navet"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.19,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgTurnip,
  },
  {
    id: nanoid(8),
    productName: ["rhubarb", "rhubarbe"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgRhubarb,
  },
  {
    id: nanoid(8),
    productName: ["scallion", "oignon vert"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 0.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgScallion,
  },
  {
    id: nanoid(8),
    productName: ["fennel", "fenouil"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.79,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgFennel,
  },
  {
    id: nanoid(8),
    productName: ["parsnip", "panais"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgParsnip,
  },
  {
    id: nanoid(8),
    productName: ["kale", "chou frisé"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.99,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgKale,
  },
  {
    id: nanoid(8),
    productName: ["watercress", "cresson"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.79,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgWaterCress,
  },
  {
    id: nanoid(8),
    productName: ["okra", "gombo"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 2.49,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgOkra,
  },
  {
    id: nanoid(8),
    productName: ["brussels-sprout", "chou de Bruxelles"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.99,
    package: "1kg",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBrusselsSprout,
  },
  {
    id: nanoid(8),
    productName: ["swiss-chard", "blette"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.69,
    package: "bunch",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgSwissChard,
  },
  {
    id: nanoid(8),
    productName: ["bok-choy", "Chou chinois"],
    category: "vegetable",
    origin: ["France", "France"],
    price: 1.49,
    package: "unity",
    totalQuantity: 100,
    status: "inStock",
    picture: productPicture.imgBokChoy,
  },
];

export default vegetablesList;
